language: objective-c
xcode_project: linphone.xcodeproj
xcode_scheme: linphone

git:
  submodules: false

env:
    global:
        - VERSION="8.1"
        - KIF_SCREENSHOTS="${TRAVIS_BUILD_DIR}/Screenshots"

install: 
    - cd submodules/build 
    - make download-sdk
    - cd ../..
    - ls -la

script:
    - export KIF_SCREENSHOTS=$TRAVIS_BUILD_DIR/Screenshots
    - mkdir -p "$KIF_SCREENSHOTS"
    - echo $KIF_SCREENSHOTS
    - xcodebuild -scheme linphone -project linphone.xcodeproj -sdk iphonesimulator8.1 test

after_failure:
    - ls -la $KIF_SCREENSHOTS
